// Generated by CoffeeScript 1.3.3
(function() {
  var App,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  jpp.util.Namespace('jpp.compass')["import"]('*');

  /*
  Application
  */


  App = (function(_super) {

    __extends(App, _super);

    function App() {
      this._clickHandler = __bind(this._clickHandler, this);
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.routes = {
      '/': 'index',
      '/about': 'about',
      '/gallery': 'gallery',
      '/gallery/<int:id>': 'item',
      '/contact': 'contact'
    };

    App.prototype._clickHandler = function(event) {
      event.preventDefault();
      return this.goto(event.currentTarget.pathname);
    };

    App.prototype.bind = function($target) {
      return $target.on("click", this._clickHandler);
    };

    App.prototype.unbind = function($target) {
      return $target.off("click", this._clickHandler);
    };

    return App;

  })(Compass);

  $(document).ready(function() {
    window.app = new App({
      root: '/example/compass/',
      isReleaseMode: false
    });
    return window.app.bind($('.navi'));
  });

  /*
  var router = new Router(
  	'/': 'index'
  	'/about': 'about'
  	'/gallery': 'gallery'
  	'/gallery/:id': 'item'
  	'/contact': 'contact'
  )
  
  router.handlers('index')
  	.onLoad  ((event) -> console.log event.path + ' load')
  	.onInit  ((event) -> console.log event.path + ' init')
  	.onGoto  ((event) -> console.log event.path + ' goto')
  	.onUnload((event) -> console.log event.path + ' unload')
  */


}).call(this);
