// Generated by CoffeeScript 1.3.3
(function() {
  var App,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  App = (function(_super) {

    __extends(App, _super);

    function App() {
      this._clickHandler = __bind(this._clickHandler, this);
      return App.__super__.constructor.apply(this, arguments);
    }

    App.prototype.routes = {
      '/': 'index',
      'about': 'about',
      'gallery': 'gallery',
      'gallery/:id': 'item',
      'contact': 'contact'
    };

    App.prototype.about = function() {
      return console.log("This is about page.");
    };

    App.prototype.item = function(id) {
      return console.log("This is gallery item " + id + " page.");
    };

    App.prototype.contact = function() {
      return console.log("This is contact page.");
    };

    App.prototype._clickHandler = function(event) {
      var path;
      event.preventDefault();
      path = event.currentTarget.pathname;
      return this.change(path);
    };

    App.prototype.bind = function($target) {
      return $target.on("click", this._clickHandler);
    };

    App.prototype.unbind = function($target) {
      return $target.off("click", this._clickHandler);
    };

    return App;

  })(Kazitori);

  $(document).ready(function() {
    window.app = new App({
      root: '/example/route/'
    });
    return window.app.bind($('.navi'));
  });

}).call(this);
